"""empty message

Revision ID: e9d46187d010
Revises: afce517ebcd2
Create Date: 2021-05-25 09:21:44.879256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d46187d010'
down_revision = 'afce517ebcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('views', sa.Integer(), nullable=True, default=0))
    op.add_column('Venue', sa.Column('views', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'views')
    op.drop_column('Venue', 'views')
    # ### end Alembic commands ###
